let text = {
	intro: [
		[-1,0,"intro2"],
		"Me:\n...",
		"Me:\n...Ugh...",
		"Me:\n...Where am I?",
		"Me:\nWhere is the light?"
	],
	intro2: [
		[0,1,"investigationRoom"],
		"Me:\nHuh?",
		"Me:\nDunno how, but the light suddenly turned on!",
		"Me:\nWait... I don't remember this room at all!",
		"Me:\nMy phone is also nowhere to be found.",
		"Me:\nThe hell is going on?!",
		"Me:\n...",
		"Me:\n...Is there any way out?"
	],
	//locker
	locker: [
		[0,1,"investigationLocker"],
		"Me:\nThere are some lockers here.",
		"Me:\nSurprisingly, one of them isn't locked.",
		"Me:\nLet's check it out."
	],
	lockerNote: [
		[1,1,"investigationLocker"],
		"Me:\nThere is a note here.",
		"Me:\nUh...",
		"Me:\nIs that a code?",
		"Me:\nDunno about programming, but I don't think code\nis meant to be printed.",
		"Me:\nIt won't help me anyways - I'm not a programmer."
	],
	lockerKey: [
		[1,1,"investigationRoom"],
		"Me:\nA key...?",
		"Me:\nI guess I'll take it.",
		"Me:\nThere isn't anything else which is useful...",
		"Me:\nGuess I'll see where I can use this key."
	],
	locker2: [
		[0,1,"investigationRoom"],
		"Me:\nMaybe this key works with one of these lockers?",
		"Me:\nNah. It is too big so it doesn't fit these keyholes."
	],
	//chest
	chestLocked: [
		[0,1,"investigationRoom"],
		"Me:\nThere is a chest here.",
		"Me:\nIt is locked though.",
		"Me:\nStill, there's probably a reason why it is here."
	],
	chestOpen: [
		[0,0,"chestOpen2"],
		"Me:\nI guess that key is meant to open that chest...",
		"Me:\nHuh, it really did open it.",
		"Me:\nLet's look into it."
	],
	chestOpen2: [
		[2,1,"investigationRoom"],
		"Me:\nA note?",
		"Me:\nIt only says that the door has been opened.",
		"Me:\nI guess there is nothing else to this chest."
	],
	//door
	doorLocked: [
		[0,1,"investigationRoom"],
		"Me:\nA door.",
		"Me:\nI don't know where it leads, but there is no harm\nin checking it out, right?",
		"Me:\n...it's locked?",
		"Me:\nAnd it looks like it is the only way outside.",
		"Me:\n...",
		"Me:\n...I hope I am not locked for eternity..."
	],
	doorKey: [
		[0,1,"investigationRoom"],
		"Me:\nMaybe this is the key to open this door?",
		"Me:\nWait... There is no keyhole.",
		"Me:\nIs there any other way to open this door?"
	],
	doorOpen: [
		[0,0,"ending"],
		"Me:\nSince the door is unlocked, let's get outta here."
	],
	//ending
	ending:[
		[3,0,"ending2"],
		"Me:\nWhat.",
		"Me:\nJust... what.",
		"Me:\nWhy would someone be so cruel...",
		"Me:\n...to first give hope to escape...",
		"Me:\nand then do this?",
		"Me:\nHuh?",
		"There is a note here...",
		"Note:\n\"Sorry, mr. Player Character,\nbut I had to make this room your whole world.\"",
		"Note:\n\"It's just because of the theme of\nLudum Dare 37 - One Room\"",
		"Note:\n\"But don't worry.\nSoon the user will close this webpage...\"",
		"Note:\n\"...and you will come back to your friends\nand family.\"",
		"Me:\n...",
		"Me:\nUh...",
		"Me:\nI think I can come up with only one possibility.",
		"Me:\nA possibility that this is a nightmare,\nand I'll just wake up in my bed."
	],
	ending2:[
		[-1,0,"logic1"],
		"Me:\n...right?",
		"Me:\n...",
		"Me:\nI don't know who is that user mentioned\nin that note...",
		"Me:\nBut...",
		"Me:\nIf he or she can hear me...",
		"Me:\nPlease.",
		"Me:\nHelp me.",
		"Me:\nClose \"this webpage\", whatever that means.",
		"Me:\nI want to get out.",
		"Me:\nDon't do this to me.",
		"Me:\nLet me wake up.",
		"Me:\nLet me go back.",
		"Me:\nPlease...",
		"Me:\n...",
		"...",
		"...",
		"...",
		"...",
		"...",
		"???:\nUm...?",
		"???:\nYou still here?",
		"???:\nOh, I haven't introduced myself yet.",
		"Dev:\nI am Developer.",
		"Dev:\nI see you aren't really satisfied with ending.",
		"Dev:\nI don't think that's surprising.",
		"Dev:\nNobody would be satisfied with that simple puzzle.",
		"Dev:\n...if you could even call that a puzzle.",
		"Dev:\nBut seriously. This is an ending.",
		"Dev:\n...",
		"Dev:\n...",
		"Dev:\n...",
		"Dev:\n...So you are determined to get more story.",
		"Dev:\nOr at least an explanation.",
		"Dev:\nYeah...",
		"Dev:\n...",
		"Dev:\n...so.",
		"Dev:\nI am going to tell you more.",
		"Dev:\nExcept you have no guarantee I say the truth.",
		"Dev:\nYou have some clues you can use to disprove\nwhatever lies I make.",
		"Dev:\nIt's time for Logic Confrontation.",
		"Dev:\nBut first...",
		"Dev:\nI should explain how you play\nthe Logic Confrontation.",
		"Dev:\nFirst, you listen each statement I say.",
		"Dev:\nIf you find a contradiction...",
		"Dev:\nYou press \"Expose\" button and select a clue\nthat my statement condradicts with.",
		"Dev:\tAnd that's all you do.",
		"Dev:\nSo, let's not waste time and begin\nthe Logic Confrontation.",
	],
	logic1:[
		[4,2,"logic1"],
		"Logic Confrontation I",
		"Clues:\nDoor Note\nLD37\nSource Code\n",
		"Dev:\nThe story you have seen is extremely simple.",
		"Dev:\nA person has been locked in the room.",
		"Dev:\nThis person wants to get out.",
		"Dev:\nAnd this person is forced to stay inside.",
		"Dev:\nAnd you make him slowly running out of oxygen.",
		"Dev:\nDon't you think you are cruel?",
		"Dev:\nClose this game and let him live his life."
	],
	logic1win:[
		"Dev:\nAh, so you aren't one of those people to\nbe tricked that zeroes and ones can\nactually live.",
		"Dev:\nIn that case, I'll tell you the story\nin an objective way.",
	],
	logic2:[
		[4,2,"logic2win"],
		"Logic Confrontation II",
		"Clues:\nSource Code\nNote in locker\nNote behind the door",
		"Dev:\nAs I said, a person has been locked in a room.",
		"Dev:\nThis person wants to get out.",
		"Dev:\nAfter short investigation, he discovers\nthat there is no exit.",
		"Dev:\nHe also discovers that he is in a game.",
		"Dev:\nI then ask you, the player, to leave.",
		"Dev:\nIt didn't work though.",
		"Dev:\nAs you decided to be persistent.",
		"Dev:\nThere is absolutely nothing more\nto this story.",
	],
	logic2win:[
		[4,0,"logic3"],
		"Dev:\nSo you noticed that note left by me.",
		"Dev:\nWell, I should expect that.",
		"Dev:\nI haven't even hidden it properly.",
		"Dev:\nSo, you probably want to know about that\nscrap of paper?",
	],
	logic3:[
		[4,2,"logic3"],
		"Logic Confrontation III",
		"Clues:\nSource Code",
		"Dev:\nThat note was nothing special.",
		"Dev:\nIt was just a snippet of code.",
		"Dev:\nWhat code? A simple copypaste one.",
		"Dev:\nIt was a stupid, lengthy oneliner.",
		"Dev:\nIt was so long that I should burn in\nhell for it.",
	],
	logic3win:[
		[4,0,"goodEnd"],
		"Dev:\nYou actually checked the source code?",
		"Dev:\nOr did you just guess?",
		"Dev:\nI am impressed anyway.",
		"Dev:\nYou might be someone clever.",
		"Dev:\nBut then, you are still there,\nfor some idiotic story.",
		"Dev:\nYou should rate other games too,\ndon't you think?",
		"Dev:\n...",
		"Dev:\nSo you are genuinely interested\nin what I have to say?",
		"Dev:\n...",
		"Dev:\nI see.",
		"Dev:\nYou probably at least skimmed through text.js,\nso there is no need to prolong this further.",
	],
	badEnd:[
		[4,0,"realEnd"],
		"Dev:\nSorry.",
		"Dev:\nI'm not in a mood taking with someone clues.",
		"Dev:\nNothing personal, but... get out."
	],
	goodEnd:[
		[-1,0,"realEnd"],
		"Dev:\nSo, the truth is...",
		"Dev:\nI wasn't feeling too creative.",
		"Dev:\nAnd I was scared that I won't make it\nin time.",
		"Dev:\nSo I made this unsatisfying story.",
		"Dev:\nThen I realized that I was almost done\nwith the coding.",
		"Dev:\nAnd it wasn't even the second day of\nthe LD.",
		"Dev:\nThen I decided to make a\nLogic Confrontation.",
		"Dev:\nNo wonder since I played Ace Attorney\nand Danganronpa.",
		"Dev:\nBut yeah.",
		"Dev:\nAs you probably know...",
		"Dev:\nThis is what I decided to call a \"good ending\"",
		"Dev:\nSo what about that person?",
		"Dev:\nNothing.",
		"Dev:\nHe didn't exist.",
		"Dev:\nIt was just a part of the bait.",
		"Dev:\nWhich you didn't bite.",
		"Dev:\nThe proof?",
		"Dev:\nYou are here.",
		"Dev:\nEven though I tried to make you go away.",
		"Dev:\nNot once.",
		"Dev:\nNot twice.",
		"Dev:\nBut even thrice.",
		"Dev:\nI don't know if you are satified or not.",
		"Dev:\nI honestly don't care.",
		"Dev:\nI made this game just because I wanted\nto do something for the jam.",
		"Dev:\nAs almost everyone participating.",
		"Dev:\nOh, I have one request for you.",
		"Dev:\nPlease don't spoil the Logic Confrontation\nstuff.",
		"Dev:\nAt least not online.",
		"Dev:\n...",
		"Dev:\nNow I really have nothing more to say.",
		"Dev:\nOh wait, there is one thing.",
		"Dev:\nIf you are going to comment on my LD\nsubmission...",
		"Dev:\nBe honest.",
		"Dev:\nI want to hear your true opinion on this game.",
		"Dev:\nNo matter how painful it seems to hear.",
		"Dev:\nAs for now...",
		"Dev:\nGoodbye."
	],
	realEnd:[
		[-1,0,"realEnd"],
		"..."
	]
}
